name: Push directory to another repository
on: push
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    environment: AzurePAT
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      env:
        AZUREPAT: ${{secrets.AZUREPAT}}
        AZUSERNAME: ${{secrets.AZUSERNAME}}
        AZUSER_EMAIL: ${{secrets.AZUSER_EMAIL}}
        AZORG: ${{secrets.AZORG}}
      run: |
        ls
        cd $GITHUB_WORKSPACE
        ls
        cd $GITHUB_WORKSPACE/Deneme-Sync
        rm -rf .git
        cd ..
        GIT_CMD_REPOSITORY="https://$AZUSERNAME:$AZUREPAT@dev.azure.com/$AZORG/Denemeler/_git/Denemeler"
        git clone $GIT_CMD_REPOSITORY
        cp -r Deneme-Sync/* Denemeler/
        cd Denemeler
        git config --global user.email "$AZUSER_EMAIL"
        git config --global user.name "$AZUSERNAME"
        git add .
        git commit -m "sync from github to azure"
        git push
      shell: bash
